# Generated by Django 5.0.6 on 2024-07-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
